### ISSUE TITLE
Add acceptance criteria for new projects

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/ecosystem#600]
At the moment, we have an informal process for vetting new ecosystem projects (check adheres to code of conduct, seems like a serious project), but it would be better to have formal requirements.

In the past, we required projects to adhere to certain testing conventions (see [Minimal requirements for projects](https://github.com/Qiskit/ecosystem/blob/main/docs/project_overview.md#minimal-requirements-for-projects)), but the testing feature is being deprecated.

**Comment by Eric-Arellano** [comment]
I'd add that they must be open source, https://opensource.org/osd/.

--

What are your stricter criteria? It'd be useful to talk through. We could consider grandfathering-in certain projects, or working with them to improve it.

**Comment by frankharkins** [comment]
Our infrastructure currently only supports projects hosted in GitHub repos, although I think we can relax that when we disable the testing feature.

Stricter criteria could be:
- Has passing(?) tests
- Uses or interfaces with Qiskit
- Supports a certain version of Qiskit (e.g. 1.0)
- Activity in past X years

Maybe we could have different requirements for different types of project? For example, we might want transpiler plugins to work with recent qiskit versions, but demo projects could be stale and inactive.

**Comment by Eric-Arellano** [comment]
That speaks to an even more fundamental question we need to answer: would we remove a project from the Ecosystem after it had been added? 

I am biased towards yes. Our ecosystem page is a service for users to find projects they can use today. It's frustrating to have to sift through out-of-date projects, especially when you don't realize it's out-of-date until you try using it.

But, I think it's important we communicate with at-risk projects and help them to avoid removal.

**Comment by mickahell** [comment]
Currently to identify such a project we had the badge color goes from purple to grey.
It was a "simple" to indicate _that project was ok at a certain time but today it doesn't comply entirely anymore_

The problem is the badge is generated after the project is submitted and so lot of project doesn't has it in their `README.md`.

We don't only support GitHub ([git cmd](https://github.com/Qiskit/ecosystem/blob/14fcc3a66df0855ffd40ef9a0adfb714e5b17ecb/ecosystem/commands/command.py#L97C69-L97C69)), we support any git project available publicly (also from GitLab, Bitbucket, ...)

To avoid removing project maybe we could archive them into another category ?

**Comment by frankharkins** [comment]
> would we remove a project from the Ecosystem after it had been added?

I think yes, but for the specific case of out-of-date projects I think there's some historical value to them. Maybe we can put them in a "stale" section at the bottom?

> To avoid removing project maybe we could archive them into another category ?

+1
